backend:
  \name: auth0
  domain: "dev-joxbbuanoe61zmps.us.auth0.com"
  client_id: "hhFoMvbGHk9y6FByNWowsiNSP891KKNQ"
  auth_redirect: "/admin/callback"

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
